name: Build and Push App

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: "linux/amd64,linux/arm64"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read the version from the file
        id: get_version
        run: echo "release_tag=$(cat ${{ inputs.app_name }}/VERSION | sed 's/v//g')" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.app_name }}
          file: ${{ inputs.app_name }}/main.dockerfile
          push: true
          platforms: ${{ inputs.platforms }}
          build-args: |
            APP_NAME=${{ inputs.app_name }}
            RELEASE_TAG=${{ steps.get_version.outputs.release_tag }}
          tags: ${{ inputs.image_name }}:latest,${{ inputs.image_name }}:${{ steps.get_version.outputs.release_tag }}
