name: Build and Push App

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string

      image_registry:
        required: false
        type: string
        default: ghcr.io/justereseau

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read the config file
        id: app_config
        run: |
          echo "tag=$(yq e '.version' ${{ inputs.app_name }}/appconfig.yaml | sed 's/v//g')" >> "$GITHUB_OUTPUT"
          echo "image=${{ inputs.image_registry }}/$(yq e '.name | downcase' ${{ inputs.app_name }}/appconfig.yaml)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.app_name }}
          file: ${{ inputs.app_name }}/main.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.app_config.outputs.image }}:latest,${{ steps.app_config.outputs.image }}:${{ steps.app_config.outputs.tag }}
