name: Deploy Images to GHCR

env:
  IMAGE_NAME: ghcr.io/justereseau/sonarr

on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read latest release
        id: get_latest_release
        run: echo "RELEASE_DATA=$(curl -s https://services.sonarr.tv/v1/releases | jq -c ."\"v3-stable\"")" >> "$GITHUB_ENV"
        shell: bash

      - name: Extract data from JSON response
        id: extract_data
        run: |
          echo "release=$(echo $RELEASE_DATA | jq -r '.version')" >> "$GITHUB_OUTPUT"
          echo "download_url=$(echo $RELEASE_DATA | jq -r '.linux.manual.url')" >> "$GITHUB_OUTPUT"
          echo "download_hash=$(echo $RELEASE_DATA | jq -r '.linux.manual.hash')" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./v3
          file: ./Dockerfile
          push: true
          build-args: |
            RELEASE_TAG=${{ steps.extract_data.outputs.release }}
            DOWNLOAD_URL=${{ steps.extract_data.outputs.download_url }}
            DOWNLOAD_HASH=${{ steps.extract_data.outputs.download_hash }}
          tags: ${{ env.IMAGE_NAME }}:v3,${{ env.IMAGE_NAME }}:${{ steps.extract_data.outputs.release }}
