name: Build Ombi

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/Build-And-Push.yaml
      - .github/workflows/Ombi.yml
      - Ombi/**

jobs:
  release:
    uses: ./.github/workflows/Build-And-Push.yaml
    with:
      app_name: Ombi
      images: '["sonarr", "radarr", "prowlarr", "ombi"]'
