name: Build Radarr

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/Build-And-Push.yaml
      - ".github/workflows/Radarr.yml"
      - "Radarr/**"

jobs:
  template:
    uses: ./.github/workflows/Build-And-Push.yaml
    with:
      app_name: Radarr
