name: Build and Push Sonarr Docker Image

env:
  IMAGE_NAME: ghcr.io/justereseau/sonarr
  PRODUCT_NAME: Sonarr

on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  sonarr_v4:
    name: Sonarr v4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read latest release
        id: get_latest_release
        run: echo "release_tag=$(curl https://api.github.com/repos/${{ env.PRODUCT_NAME }}/${{ env.PRODUCT_NAME }}/releases/latest --silent | jq -r '.tag_name' | sed 's/v//g')" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            RELEASE_TAG=${{ steps.get_latest_release.outputs.release_tag }}
            PRODUCT_NAME=${{ env.PRODUCT_NAME }}
            BRANCH_NAME=main
            OS_NAME=linux-musl
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.get_latest_release.outputs.release_tag }}
